/**
 * data.js – Mock data for Dietopia
 * All fake data used across the application
 */

// ---------- User Profile (mock current user) ----------
const USER = {
  name: "Alex García",
  email: "alex@example.com",
  avatar: "🧑‍💻",
  weight: 75,
  height: 175,
  age: 28,
  goal: "lose_weight",
  goalLabel: "Perder peso",
  restrictions: ["lactose_free"],
  budget: 60,
  planningType: "weekly",
  daysActive: 12,
  streak: 5,
  compliance: 78,
};

// ---------- Weekly Meal Plan (mock diet) ----------
const MEAL_PLAN = {
  week: "28 Abr – 4 May 2025",
  calories_target: 1800,
  days: [
    {
      id: 0,
      day: "Lunes",
      date: "28 Abr",
      meals: {
        breakfast: {
          id: "b0",
          name: "Avena con frutas del bosque",
          emoji: "🍓",
          calories: 320,
          time: "8:00",
          tags: ["Sin lactosa", "Alto en fibra"],
          ingredients: ["80g avena", "150ml leche de avena", "50g arándanos", "1 cucharada de miel"],
          recipe: "Mezcla la avena con la leche de avena y calienta 2 min en microondas. Añade los arándanos y la miel por encima.",
          macros: { protein: 10, carbs: 58, fat: 6 },
        },
        lunch: {
          id: "l0",
          name: "Ensalada de pollo y aguacate",
          emoji: "🥗",
          calories: 480,
          time: "13:30",
          tags: ["Alto en proteína", "Fresco"],
          ingredients: ["150g pechuga de pollo", "1 aguacate", "100g lechuga mixta", "Tomates cherry", "Aceite de oliva"],
          recipe: "Cocina el pollo a la plancha. Mezcla la lechuga, el aguacate y los tomates. Añade el pollo y aliña con aceite.",
          macros: { protein: 38, carbs: 14, fat: 22 },
        },
        snack: {
          id: "s0",
          name: "Manzana con almendras",
          emoji: "🍎",
          calories: 200,
          time: "16:30",
          tags: ["Natural"],
          ingredients: ["1 manzana grande", "20g almendras"],
          recipe: "Sirve la manzana cortada en gajos junto con las almendras.",
          macros: { protein: 4, carbs: 28, fat: 9 },
        },
        dinner: {
          id: "d0",
          name: "Salmón al vapor con brócoli",
          emoji: "🐟",
          calories: 420,
          time: "20:30",
          tags: ["Omega-3", "Sin gluten"],
          ingredients: ["200g salmón", "200g brócoli", "1 limón", "Eneldo", "Aceite de oliva"],
          recipe: "Cocina el salmón al vapor 12 min. Cuece el brócoli 5 min. Sirve con zumo de limón y eneldo.",
          macros: { protein: 36, carbs: 10, fat: 24 },
        },
      },
    },
    {
      id: 1,
      day: "Martes",
      date: "29 Abr",
      meals: {
        breakfast: {
          id: "b1",
          name: "Tostadas de aguacate y huevo",
          emoji: "🥑",
          calories: 380,
          time: "8:00",
          tags: ["Alto en proteína"],
          ingredients: ["2 rebanadas pan integral", "1 aguacate", "2 huevos", "Sal", "Pimienta"],
          recipe: "Tuesta el pan, aplasta el aguacate y ponlo encima. Cuece los huevos al gusto y añádelos.",
          macros: { protein: 18, carbs: 42, fat: 18 },
        },
        lunch: {
          id: "l1",
          name: "Lentejas con verduras",
          emoji: "🫘",
          calories: 520,
          time: "13:30",
          tags: ["Alto en fibra", "Vegano"],
          ingredients: ["200g lentejas cocidas", "1 zanahoria", "1 puerro", "1 tomate", "Especias"],
          recipe: "Sofríe el puerro y la zanahoria. Añade las lentejas y el tomate. Cuece 15 min con las especias.",
          macros: { protein: 22, carbs: 68, fat: 4 },
        },
        snack: {
          id: "s1",
          name: "Yogur de coco con granola",
          emoji: "🥥",
          calories: 220,
          time: "16:30",
          tags: ["Sin lactosa"],
          ingredients: ["150g yogur de coco", "30g granola", "1 cucharada de semillas de chía"],
          recipe: "Mezcla el yogur con las semillas. Añade la granola por encima.",
          macros: { protein: 6, carbs: 32, fat: 8 },
        },
        dinner: {
          id: "d1",
          name: "Pollo al horno con patatas",
          emoji: "🍗",
          calories: 500,
          time: "20:30",
          tags: ["Sin gluten"],
          ingredients: ["200g muslo de pollo", "2 patatas medianas", "Romero", "Ajo", "Aceite de oliva"],
          recipe: "Hornea el pollo y las patatas 40 min a 200°C con ajo, romero y aceite.",
          macros: { protein: 34, carbs: 48, fat: 16 },
        },
      },
    },
    {
      id: 2,
      day: "Miércoles",
      date: "30 Abr",
      meals: {
        breakfast: {
          id: "b2",
          name: "Batido verde energético",
          emoji: "🥤",
          calories: 290,
          time: "7:30",
          tags: ["Vegano", "Energizante"],
          ingredients: ["1 plátano", "1 puñado de espinacas", "200ml leche de almendras", "1 kiwi"],
          recipe: "Tritura todos los ingredientes en la batidora hasta obtener una mezcla suave.",
          macros: { protein: 6, carbs: 54, fat: 5 },
        },
        lunch: {
          id: "l2",
          name: "Pasta con salsa de tomate y atún",
          emoji: "🍝",
          calories: 560,
          time: "14:00",
          tags: ["Alto en proteína"],
          ingredients: ["180g pasta integral", "1 lata de atún", "Salsa de tomate casera", "Albahaca"],
          recipe: "Cuece la pasta. Mezcla con la salsa de tomate y el atún. Sirve con albahaca fresca.",
          macros: { protein: 32, carbs: 76, fat: 10 },
        },
        snack: {
          id: "s2",
          name: "Plátano y nueces",
          emoji: "🍌",
          calories: 190,
          time: "16:30",
          tags: ["Natural", "Energía rápida"],
          ingredients: ["1 plátano", "20g nueces"],
          recipe: "Sirve el plátano con las nueces.",
          macros: { protein: 4, carbs: 30, fat: 8 },
        },
        dinner: {
          id: "d2",
          name: "Tortilla de verduras",
          emoji: "🥚",
          calories: 360,
          time: "20:00",
          tags: ["Vegetariano"],
          ingredients: ["3 huevos", "1 pimiento", "1 cebolla", "1 calabacín", "Aceite de oliva"],
          recipe: "Sofríe las verduras. Bate los huevos y mézclalos. Cuaja en la sartén a fuego medio.",
          macros: { protein: 22, carbs: 18, fat: 22 },
        },
      },
    },
    {
      id: 3,
      day: "Jueves",
      date: "1 May",
      meals: {
        breakfast: {
          id: "b3",
          name: "Pancakes de avena y plátano",
          emoji: "🥞",
          calories: 400,
          time: "8:30",
          tags: ["Sin gluten", "Dulce natural"],
          ingredients: ["100g avena molida", "1 plátano", "2 huevos", "1 cucharadita de canela"],
          recipe: "Tritura todos los ingredientes. Cuaja pequeñas tortitas en sartén antiadherente 2 min por lado.",
          macros: { protein: 16, carbs: 62, fat: 10 },
        },
        lunch: {
          id: "l3",
          name: "Ensalada de garbanzos",
          emoji: "🥙",
          calories: 490,
          time: "13:30",
          tags: ["Vegano", "Alto en fibra"],
          ingredients: ["200g garbanzos cocidos", "Pepino", "Tomate", "Cebolla morada", "Perejil", "Limón"],
          recipe: "Mezcla todos los ingredientes. Aliña con zumo de limón y aceite de oliva.",
          macros: { protein: 20, carbs: 64, fat: 12 },
        },
        snack: {
          id: "s3",
          name: "Naranja y pistachos",
          emoji: "🍊",
          calories: 180,
          time: "17:00",
          tags: ["Natural"],
          ingredients: ["1 naranja grande", "20g pistachos"],
          recipe: "Pela la naranja y sirve con los pistachos.",
          macros: { protein: 5, carbs: 26, fat: 7 },
        },
        dinner: {
          id: "d3",
          name: "Merluza al ajillo con espárragos",
          emoji: "🐠",
          calories: 380,
          time: "20:30",
          tags: ["Bajo en calorías", "Sin gluten"],
          ingredients: ["200g merluza", "10 espárragos", "4 dientes de ajo", "Aceite de oliva", "Perejil"],
          recipe: "Dora el ajo en aceite. Añade la merluza y cuece 8 min. Sirve con espárragos a la plancha.",
          macros: { protein: 38, carbs: 8, fat: 18 },
        },
      },
    },
    {
      id: 4,
      day: "Viernes",
      date: "2 May",
      meals: {
        breakfast: {
          id: "b4",
          name: "Chia pudding con mango",
          emoji: "🥭",
          calories: 310,
          time: "8:00",
          tags: ["Sin lactosa", "Omega-3"],
          ingredients: ["40g semillas de chía", "250ml leche de coco", "1/2 mango", "1 cucharadita de vainilla"],
          recipe: "Mezcla chía con leche de coco. Refrigera toda la noche. Sirve con mango troceado.",
          macros: { protein: 8, carbs: 42, fat: 14 },
        },
        lunch: {
          id: "l4",
          name: "Bowl de arroz con verduras",
          emoji: "🍱",
          calories: 530,
          time: "13:30",
          tags: ["Vegano", "Equilibrado"],
          ingredients: ["150g arroz integral", "Edamame", "Zanahoria", "Pepino", "Salsa de soja", "Sésamo"],
          recipe: "Cuece el arroz. Prepara las verduras. Monta el bowl y aliña con salsa de soja y sésamo.",
          macros: { protein: 18, carbs: 84, fat: 8 },
        },
        snack: {
          id: "s4",
          name: "Barritas de dátil y avena",
          emoji: "🍫",
          calories: 240,
          time: "16:30",
          tags: ["Natural", "Energía sostenida"],
          ingredients: ["100g dátiles", "60g avena", "20g almendras trituradas"],
          recipe: "Tritura los dátiles. Mezcla con avena y almendras. Compacta y refrigera 1 hora. Corta en barras.",
          macros: { protein: 6, carbs: 44, fat: 7 },
        },
        dinner: {
          id: "d4",
          name: "Pizza de coliflor con tomate",
          emoji: "🍕",
          calories: 420,
          time: "20:30",
          tags: ["Sin gluten", "Bajo en carbos"],
          ingredients: ["1 coliflor grande", "2 huevos", "Salsa de tomate", "Orégano", "Verduras al gusto"],
          recipe: "Tritura la coliflor. Mezcla con huevos. Forma la base y hornea 20 min. Añade toppings y hornea 10 min más.",
          macros: { protein: 20, carbs: 32, fat: 18 },
        },
      },
    },
    {
      id: 5,
      day: "Sábado",
      date: "3 May",
      meals: {
        breakfast: {
          id: "b5",
          name: "Granola casera con frutas",
          emoji: "🫐",
          calories: 360,
          time: "9:00",
          tags: ["Vegano"],
          ingredients: ["80g granola", "200ml leche de almendras", "1 puñado de fresas", "1 kiwi"],
          recipe: "Sirve la granola con la leche de almendras. Añade las frutas por encima.",
          macros: { protein: 8, carbs: 62, fat: 12 },
        },
        lunch: {
          id: "l5",
          name: "Tacos de tofu y aguacate",
          emoji: "🌮",
          calories: 510,
          time: "14:00",
          tags: ["Vegano", "Sin gluten"],
          ingredients: ["200g tofu firme", "2 tortillas de maíz", "1 aguacate", "Pico de gallo", "Lima"],
          recipe: "Marina el tofu y cocínalo a la plancha. Monta los tacos con aguacate y pico de gallo. Añade zumo de lima.",
          macros: { protein: 22, carbs: 48, fat: 22 },
        },
        snack: {
          id: "s5",
          name: "Smoothie de fresas",
          emoji: "🍓",
          calories: 170,
          time: "17:00",
          tags: ["Bajo en calorías"],
          ingredients: ["150g fresas", "100ml yogur de coco", "1 cucharadita de miel"],
          recipe: "Tritura todos los ingredientes hasta que quede cremoso.",
          macros: { protein: 4, carbs: 34, fat: 3 },
        },
        dinner: {
          id: "d5",
          name: "Cena especial: Paella de verduras",
          emoji: "🥘",
          calories: 550,
          time: "21:00",
          tags: ["Vegano", "Festivo"],
          ingredients: ["200g arroz", "Pimiento rojo y verde", "Tomate", "Judías verdes", "Azafrán", "Caldo de verduras"],
          recipe: "Sofríe las verduras. Añade el arroz y el azafrán. Vierte el caldo caliente y cuece 18 min sin remover.",
          macros: { protein: 12, carbs: 96, fat: 8 },
        },
      },
    },
    {
      id: 6,
      day: "Domingo",
      date: "4 May",
      meals: {
        breakfast: {
          id: "b6",
          name: "Brunch: Huevos Benedict vegano",
          emoji: "🍳",
          calories: 440,
          time: "10:00",
          tags: ["Vegano", "Especial"],
          ingredients: ["2 huevos pochados", "Pan integral", "Espinacas", "Tomate", "Salsa holandesa vegana"],
          recipe: "Pocha los huevos. Tuesta el pan. Monta con espinacas, tomate y salsa holandesa.",
          macros: { protein: 18, carbs: 46, fat: 20 },
        },
        lunch: {
          id: "l6",
          name: "Sopa de verduras reconfortante",
          emoji: "🍜",
          calories: 350,
          time: "14:00",
          tags: ["Vegano", "Ligero"],
          ingredients: ["Zanahoria", "Apio", "Puerro", "Patata", "Caldo de verduras", "Tomillo"],
          recipe: "Sofríe las verduras. Añade el caldo y cuece 30 min. Tritura parcialmente para cremosidad.",
          macros: { protein: 8, carbs: 58, fat: 6 },
        },
        snack: {
          id: "s6",
          name: "Uvas y queso vegano",
          emoji: "🍇",
          calories: 200,
          time: "17:00",
          tags: ["Natural"],
          ingredients: ["150g uvas", "50g queso vegano"],
          recipe: "Sirve las uvas lavadas con el queso vegano.",
          macros: { protein: 6, carbs: 28, fat: 8 },
        },
        dinner: {
          id: "d6",
          name: "Curry de garbanzos y espinacas",
          emoji: "🍛",
          calories: 480,
          time: "20:00",
          tags: ["Vegano", "Reconfortante"],
          ingredients: ["200g garbanzos cocidos", "100g espinacas", "Leche de coco", "Curry en polvo", "Cebolla", "Ajo"],
          recipe: "Sofríe cebolla y ajo. Añade el curry y la leche de coco. Incorpora los garbanzos y las espinacas. Cuece 15 min.",
          macros: { protein: 16, carbs: 56, fat: 18 },
        },
      },
    },
  ],
};

// ---------- Shopping List ----------
const SHOPPING_LIST = [
  // Produce
  { id: "p1", category: "Frutas y Verduras", name: "Aguacates", qty: "3 unidades", price: 2.10, unit_price: 0.70, alternatives: ["Marca blanca: 0.55€/ud"], emoji: "🥑", owned: false, removed: false },
  { id: "p2", category: "Frutas y Verduras", name: "Arándanos", qty: "200g", price: 2.50, unit_price: 2.50, alternatives: ["Congelados: 1.20€"], emoji: "🫐", owned: false, removed: false },
  { id: "p3", category: "Frutas y Verduras", name: "Manzanas", qty: "4 unidades", price: 1.60, unit_price: 0.40, alternatives: ["Manzana Granny Smith: 0.35€/ud"], emoji: "🍎", owned: false, removed: false },
  { id: "p4", category: "Frutas y Verduras", name: "Plátanos", qty: "1 racimo (6 ud)", price: 1.20, unit_price: 0.20, alternatives: [], emoji: "🍌", owned: false, removed: false },
  { id: "p5", category: "Frutas y Verduras", name: "Brócoli", qty: "1 pieza", price: 1.50, unit_price: 1.50, alternatives: ["Congelado: 0.90€"], emoji: "🥦", owned: false, removed: false },
  { id: "p6", category: "Frutas y Verduras", name: "Espinacas baby", qty: "250g bolsa", price: 1.80, unit_price: 1.80, alternatives: ["Espinacas normales: 1.20€"], emoji: "🌿", owned: false, removed: false },
  { id: "p7", category: "Frutas y Verduras", name: "Fresas", qty: "500g", price: 2.20, unit_price: 2.20, alternatives: ["Congeladas: 1.50€"], emoji: "🍓", owned: false, removed: false },
  { id: "p8", category: "Frutas y Verduras", name: "Naranjas", qty: "1kg", price: 1.40, unit_price: 1.40, alternatives: [], emoji: "🍊", owned: false, removed: false },
  // Proteins
  { id: "pr1", category: "Proteínas", name: "Pechuga de pollo", qty: "600g", price: 5.40, unit_price: 9.0, alternatives: ["Muslos: 4.20€"], emoji: "🍗", owned: false, removed: false },
  { id: "pr2", category: "Proteínas", name: "Salmón fresco", qty: "300g", price: 7.80, unit_price: 26.0, alternatives: ["Salmón congelado: 5.60€", "Trucha: 6.20€"], emoji: "🐟", owned: false, removed: false },
  { id: "pr3", category: "Proteínas", name: "Merluza", qty: "400g", price: 5.60, unit_price: 14.0, alternatives: ["Merluza congelada: 3.80€"], emoji: "🐠", owned: false, removed: false },
  { id: "pr4", category: "Proteínas", name: "Atún en lata", qty: "3 latas (80g c/u)", price: 2.70, unit_price: 0.90, alternatives: ["Marca blanca: 0.65€/lata"], emoji: "🐡", owned: false, removed: false },
  { id: "pr5", category: "Proteínas", name: "Huevos", qty: "12 unidades", price: 2.40, unit_price: 0.20, alternatives: ["Camperos M: 3.20€"], emoji: "🥚", owned: false, removed: false },
  // Grains
  { id: "g1", category: "Cereales y Legumbres", name: "Avena integral", qty: "500g", price: 1.80, unit_price: 3.60, alternatives: ["Avena fina: 1.40€"], emoji: "🌾", owned: false, removed: false },
  { id: "g2", category: "Cereales y Legumbres", name: "Pasta integral", qty: "500g", price: 1.60, unit_price: 3.20, alternatives: ["Marca blanca: 1.10€"], emoji: "🍝", owned: false, removed: false },
  { id: "g3", category: "Cereales y Legumbres", name: "Arroz integral", qty: "1kg", price: 2.20, unit_price: 2.20, alternatives: ["Marca blanca: 1.60€"], emoji: "🍚", owned: false, removed: false },
  { id: "g4", category: "Cereales y Legumbres", name: "Lentejas cocidas (bote)", qty: "2 botes", price: 1.60, unit_price: 0.80, alternatives: ["Lentejas secas 500g: 1.20€"], emoji: "🫘", owned: false, removed: false },
  { id: "g5", category: "Cereales y Legumbres", name: "Garbanzos cocidos (bote)", qty: "2 botes", price: 1.80, unit_price: 0.90, alternatives: ["Secos 500g: 1.40€"], emoji: "🟡", owned: false, removed: false },
  // Pantry
  { id: "pa1", category: "Despensa", name: "Aceite de oliva virgen extra", qty: "750ml", price: 4.90, unit_price: 4.90, alternatives: ["Aceite de girasol: 2.20€"], emoji: "🫒", owned: false, removed: false },
  { id: "pa2", category: "Despensa", name: "Leche de avena", qty: "1L", price: 1.50, unit_price: 1.50, alternatives: ["Leche de almendras: 1.80€", "Leche entera: 0.90€"], emoji: "🥛", owned: false, removed: false },
  { id: "pa3", category: "Despensa", name: "Semillas de chía", qty: "200g", price: 2.80, unit_price: 2.80, alternatives: [], emoji: "⚫", owned: false, removed: false },
  { id: "pa4", category: "Despensa", name: "Almendras", qty: "200g", price: 2.60, unit_price: 2.60, alternatives: ["Mezcla de frutos secos: 2.20€"], emoji: "🥜", owned: false, removed: false },
];

// ---------- Progress Data ----------
const PROGRESS_DATA = {
  compliance_history: [60, 70, 65, 75, 78, 82, 80, 85, 78, 82, 88, 92],
  weeks: ["Sem 1", "Sem 2", "Sem 3", "Sem 4", "Sem 5", "Sem 6", "Sem 7", "Sem 8", "Sem 9", "Sem 10", "Sem 11", "Sem 12"],
  goals: {
    current_weight: 75.2,
    target_weight: 70.0,
    start_weight: 82.0,
  },
  nutrients_weekly: {
    calories: { current: 1780, target: 1800 },
    protein: { current: 110, target: 120 },
    carbs: { current: 210, target: 200 },
    fat: { current: 62, target: 60 },
  },
  achievements: [
    { icon: "🔥", label: "5 días seguidos", done: true },
    { icon: "🥗", label: "Primera semana completada", done: true },
    { icon: "💧", label: "Hidratación diaria", done: true },
    { icon: "🎯", label: "Primera meta alcanzada", done: false },
    { icon: "🏆", label: "Mes completo", done: false },
  ],
};

// ---------- Alternative Meals (for replacement feature) ----------
const ALTERNATIVE_MEALS = [
  {
    id: "alt1", name: "Tortilla española", emoji: "🥚", calories: 400,
    tags: ["Vegetariano", "Clásico"],
    macros: { protein: 18, carbs: 32, fat: 22 },
  },
  {
    id: "alt2", name: "Ensalada César con tofu", emoji: "🥗", calories: 350,
    tags: ["Vegano", "Fresco"],
    macros: { protein: 20, carbs: 22, fat: 16 },
  },
  {
    id: "alt3", name: "Sándwich integral con hummus", emoji: "🥙", calories: 380,
    tags: ["Vegano"],
    macros: { protein: 14, carbs: 52, fat: 12 },
  },
  {
    id: "alt4", name: "Crema de zanahoria", emoji: "🍲", calories: 280,
    tags: ["Vegano", "Bajo en calorías"],
    macros: { protein: 6, carbs: 42, fat: 8 },
  },
  {
    id: "alt5", name: "Poke bowl de salmón", emoji: "🍱", calories: 520,
    tags: ["Alto en proteína", "Omega-3"],
    macros: { protein: 34, carbs: 58, fat: 16 },
  },
  {
    id: "alt6", name: "Quesadillas de verduras", emoji: "🫓", calories: 460,
    tags: ["Vegetariano"],
    macros: { protein: 18, carbs: 56, fat: 18 },
  },
];

// ---------- Supermarkets (for guided shopping) ----------
const SUPERMARKETS = [
  { id: "mercadona", name: "Mercadona", emoji: "🟢", color: "#009E61" },
  { id: "lidl", name: "Lidl", emoji: "🔵", color: "#0050AA" },
  { id: "alcampo", name: "Alcampo", emoji: "🔴", color: "#E30613" },
];

// ---------- Testimonials (for login page) ----------
const TESTIMONIALS = [
  {
    text: "Dietopia cambió mi forma de comer. Ahorro 40€ al mes en la compra.",
    author: "María L.",
    role: "Diseñadora UX",
    avatar: "👩‍🎨",
  },
  {
    text: "En 2 semanas mejoré mis hábitos sin esfuerzo. Super recomendado.",
    author: "Carlos M.",
    role: "Desarrollador",
    avatar: "👨‍💻",
  },
  {
    text: "Perfecto para personas sin tiempo. Las recetas son deliciosas.",
    author: "Ana P.",
    role: "Médico",
    avatar: "👩‍⚕️",
  },
];

// ---------- Value Propositions (for landing) ----------
const VALUE_PROPS = [
  { icon: "⏱️", title: "Ahorra tiempo", desc: "Tu plan semanal listo en segundos, sin pensar qué cocinar." },
  { icon: "💸", title: "Gasta menos", desc: "Lista de la compra optimizada para reducir desperdicio y coste." },
  { icon: "🥦", title: "Come mejor", desc: "Dietas personalizadas según tus objetivos y restricciones." },
  { icon: "🧠", title: "Cero esfuerzo", desc: "La IA hace la planificación. Tú solo disfrutas comiendo." },
];

// ---------- AI Loading Messages ----------
const AI_MESSAGES = [
  "Analizando tu perfil...",
  "Calculando requerimientos nutricionales...",
  "Buscando recetas compatibles...",
  "Optimizando balance de macronutrientes...",
  "Ajustando al presupuesto...",
  "Verificando restricciones alimentarias...",
  "Generando plan semanal...",
  "¡Casi listo!",
];

// Export everything (works via global scope for non-module pages)
if (typeof window !== "undefined") {
  window.DietopiaData = {
    USER,
    MEAL_PLAN,
    SHOPPING_LIST,
    PROGRESS_DATA,
    ALTERNATIVE_MEALS,
    SUPERMARKETS,
    TESTIMONIALS,
    VALUE_PROPS,
    AI_MESSAGES,
  };
}
